MEMBER_BOOLEAN_PERMISSIONS = {
    "send_messages",
    "add_members",
    "pin_messages",
    "edit_own_tags",
    "change_group_info",
    "send_photos",
    "send_video_files",
    "send_video_messages",
    "send_music",
    "send_voice_messages",
    "send_files",
    "send_stickers_gifs",
    "embed_links",
    "send_polls",
    "send_reactions",
}

MEMBER_NUMERIC_PERMISSIONS = {
    "slowmode_seconds",
}

ADMIN_PERMISSIONS = {
    "change_group_info",
    "delete_messages",
    "ban_users",
    "add_members",
    "pin_messages",
    "post_stories",
    "edit_others_stories",
    "delete_others_stories",
    "manage_video_chats",
    "edit_member_tags",
    "remain_anonymous",
    "manage_admins",
}

ADMIN_MEMBER_OVERLAP_PERMISSIONS = ADMIN_PERMISSIONS & MEMBER_BOOLEAN_PERMISSIONS

SYSTEM_ROLE_DEFAULTS = {
    "member": {
        "send_messages": True,
        "add_members": True,
        "pin_messages": True,
        "edit_own_tags": False,
        "change_group_info": True,
        "send_photos": True,
        "send_video_files": True,
        "send_video_messages": True,
        "send_music": True,
        "send_voice_messages": True,
        "send_files": True,
        "send_stickers_gifs": True,
        "embed_links": True,
        "send_polls": True,
        "send_reactions": True,
        "slowmode_seconds": 0,
    },
    "admin": {
        "send_messages": True,
        "add_members": True,
        "pin_messages": True,
        "edit_own_tags": True,
        "change_group_info": True,
        "send_photos": True,
        "send_video_files": True,
        "send_video_messages": True,
        "send_music": True,
        "send_voice_messages": True,
        "send_files": True,
        "send_stickers_gifs": True,
        "embed_links": True,
        "send_polls": True,
        "send_reactions": True,
        "delete_messages": True,
        "ban_users": True,
        "post_stories": False,
        "edit_others_stories": False,
        "delete_others_stories": False,
        "manage_video_chats": True,
        "edit_member_tags": True,
        "remain_anonymous": False,
        "manage_admins": False,
        "slowmode_seconds": 0,
    },
}

OWNER_PERMISSIONS = {
    "send_messages": True,
    "add_members": True,
    "pin_messages": True,
    "edit_own_tags": True,
    "change_group_info": True,
    "send_photos": True,
    "send_video_files": True,
    "send_video_messages": True,
    "send_music": True,
    "send_voice_messages": True,
    "send_files": True,
    "send_stickers_gifs": True,
    "embed_links": True,
    "send_polls": True,
    "send_reactions": True,
    "delete_messages": True,
    "ban_users": True,
    "post_stories": True,
    "edit_others_stories": True,
    "delete_others_stories": True,
    "manage_video_chats": True,
    "edit_member_tags": True,
    "remain_anonymous": True,
    "manage_admins": True,
    "slowmode_seconds": 0,
}
