"""add chat permissions

Revision ID: 37e46d690c9d
Revises: 202606130002
Create Date: 2026-06-18 20:38:40.704144+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '37e46d690c9d'
down_revision: Union[str, None] = '202606130002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_member_permissions',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.add_column('chat_participants', sa.Column('admin_permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('chat_participants', sa.Column('promoted_by', sa.Integer(), nullable=True))
    op.add_column('chat_participants', sa.Column('promoted_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(
        'fk_chat_participants_promoted_by_users',
        'chat_participants',
        'users',
        ['promoted_by'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_chat_participants_promoted_by_users',
        'chat_participants',
        type_='foreignkey',
    )
    op.drop_column('chat_participants', 'promoted_at')
    op.drop_column('chat_participants', 'promoted_by')
    op.drop_column('chat_participants', 'admin_permissions')
    op.drop_table('chat_member_permissions')
    # ### end Alembic commands ###
