"""add message deleted by

Revision ID: 920334026cd8
Revises: 6e4a453dff7a
Create Date: 2026-06-20 16:01:56.249335+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '920334026cd8'
down_revision: Union[str, None] = '6e4a453dff7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_messages_deleted_by_users',
        'messages',
        'users',
        ['deleted_by'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_messages_deleted_by_users', 'messages', type_='foreignkey')
    op.drop_column('messages', 'deleted_by')
    # ### end Alembic commands ###
