"""replace message deletions with message user states

Revision ID: 6e4a453dff7a
Revises: 37e46d690c9d
Create Date: 2026-06-19 23:15:02.352853+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6e4a453dff7a'
down_revision: Union[str, None] = '37e46d690c9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_user_states',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('pinned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'user_id')
    )
    op.execute("""
        INSERT INTO message_user_states (message_id, user_id, deleted_at)
        SELECT message_id, user_id, deleted_at
        FROM message_deletions
    """)
    op.drop_table('message_deletions')
    op.add_column('messages', sa.Column('pinned_at', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('pinned_by', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_messages_pinned_by_users',
        'messages',
        'users',
        ['pinned_by'],
        ['id'],
        ondelete='SET NULL',
    )
    op.drop_column('messages', 'is_pinned')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_pinned', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_constraint('fk_messages_pinned_by_users', 'messages', type_='foreignkey')
    op.drop_column('messages', 'pinned_by')
    op.drop_column('messages', 'pinned_at')
    op.create_table('message_deletions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('message_deletions_message_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('message_deletions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('message_deletions_pkey')),
    sa.UniqueConstraint('message_id', 'user_id', name=op.f('message_deletions_message_id_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.execute("""
        INSERT INTO message_deletions (message_id, user_id, deleted_at)
        SELECT message_id, user_id, deleted_at
        FROM message_user_states
        WHERE deleted_at IS NOT NULL
    """)
    op.drop_table('message_user_states')
    # ### end Alembic commands ###
